---
- name: Create Nutanix VM
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Nutanix VM
    ntnx_vm:
      state: present
      nutanix_host: "{{ ip }}"
      nutanix_username: "{{ username }}"
      nutanix_password: "{{ password }}"
      validate_certs: false
      name: "RHEL 8 VM"
      cluster:
        name: "{{ cluster_name }}"   
      networks:
        - is_connected: True
          subnet:
            name: "{{ network_name }}"
      disks:
        - type: "DISK"
          size_gb: 100
          bus: "PCI"
      vcpus: 4
      memory_gb: 8
      timezone: UTC
