collections:
- name: community.vmware
  source: https://3.86.109.168/api/galaxy/content/community/
- name: redhat.openshift
  source: https://3.86.109.168/api/galaxy/content/rh-certified/
- name: vmware.vmware_rest
  source: https://3.86.109.168/api/galaxy/content/rh-certified/
- name: community.general
  source: https://3.86.109.168/api/galaxy/content/community/
- name: kubevirt.core
  source: https://3.86.109.168/api/galaxy/content/community/
