collections:
- name: community.vmware
  source: https://3.86.109.168/pulp_ansible/galaxy/community/
- name: redhat.openshift
  source: https://3.86.109.168/pulp_ansible/galaxy/rh-certified/
- name: vmware.vmware_rest
  source: https://3.86.109.168/pulp_ansible/galaxy/rh-certified/
- name: community.general
  source: https://3.86.109.168/pulp_ansible/galaxy/community/
- name: kubevirt.core
  source: https://3.86.109.168/pulp_ansible/galaxy/rh-certified/
