---
- name: Gather Nutanix Cluster Info
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Gather Cluster Info
    nutanix.ncp.ntnx_clusters_info:
      nutanix_host: "{{ ip }}"
      nutanix_username: "{{ username }}"
      nutanix_password: "{{ password }}"
      nutanix_port: 9440
      validate_certs: false
    register: cluster_result

  - name: Print Cluster Info
    debug:
      var: cluster_result
