---
- name: Create Nutanix VM
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Nutanix VM
    nutanix.ncp.ntnx_vms:
      state: present
      nutanix_host: "{{ ip }}"
      nutanix_username: "{{ username }}"
      nutanix_password: "{{ password }}"
#      nutanix_port: 443
      validate_certs: false
      name: "{{ vm_name }}"
      cluster:
        name: "{{ cluster_name }}"   
      networks:
        - is_connected: True
          subnet:
            name: "{{ network_name }}"
      disks:
        - type: "DISK"
          size_gb: 100
          bus: "SCSI"
      vcpus: 4
      memory_gb: 8
      timezone: UTC
