---
- name: Create Nutanix VM
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create Nutanix VM
    nutanix.ncp.ntnx_vms:
      state: present
      nutanix_host: "{{ ip }}"
      nutanix_username: "{{ username }}"
      nutanix_password: "{{ password }}"
      nutanix_port: 9440
      validate_certs: false
      name: "{{ vm_name }}"
      cluster:
        name: "Arthrex-AAP-Demo"    
      networks:
        - is_connected: True
          subnet:
            name: "Primary"
      disks:
        - type: "DISK"
          size_gb: 75
          clone_image:
            name: "RHEL8_Base_OS"
          bus: "SCSI"
      vcpus: 4
      memory_gb: 8
      timezone: UTC
