---
- name: Delete Nutanix VVM
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Delete VM
    nutanix.ncp.ntnx_vms:
      state: absent
      nutanix_host: "{{ ip }}"
      nutanix_username: "{{ username }}"
      nutanix_password: "{{ password }}"
      validate_certs: false
      vm_uuid: "{{ vm_uuid }}"
