---
- name: Query VM IP information
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Get IP from vCenter
      vmware.vmware.guest_info:
        validate_certs: false
        name: "vm-test-demo"
      register: vm_info

    - name: Display VM information
      debug:
        var: vm_info.guests[0].ipv4

    - name: Set IPv4 as a fact
      set_fact:
        vm_ip: "{{ vm_info.guests[0].ipv4 }}"

    - name: Add new VM to temporary inventory group
      ansible.builtin.add_host:
        name: "{{ vm_ip }}"
        groups: new_provisioned_vms
        ansible_user: root
        ansible_ssh_pass: "{{ demo_password }}"
        ansible_ssh_common_args: >
          -o ProxyCommand="sshpass -p {{ bastion_password }} -W %h:%p -q "{{bastion_user}}"@"{{bastion_host}}"
          -o StrictHostKeyChecking=no

- name: Configure the new VM
  hosts: new_provisioned_vms
  gather_facts: true
  tasks:
    - name: Set Host Name
      ansible.builtin.hostname:
        name: "vm-test-demo"
        use: systemd

    - name: Register system
      ansible.builtin.command: subscription-manager register --username {{ rh_username }} --password {{ rh_password }} --auto-attach

    - name: Update security packages 
      dnf:
        name: "*"
        state: latest
        security: true

    