---
- name: Deploy VM from Folder Template
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create A Folder Using An Absolute Path
    vmware.vmware.folder:
      validate_certs: false
      datacenter: "SDDC-Datacenter"
      relative_path: Workloads/sandbox-j7ttn/Templates
      state: present