---
- name: Power off VM
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Set the state of a virtual machine to poweroff
    vmware.vmware.vm_powerstate:
      datacenter: "SDDC-Datacenter"
      folder: "Workloads/sandbox-j7ttn"
      name: "vm-test-demo"
      validate_certs: false
      state: powered-off
    register: poweroff