---
- name: Deploy VM from Folder Template
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create VM from template
      vmware.vmware.deploy_folder_template:
        validate_certs: false
        datacenter: "SDDC-Datacenter"
        cluster: Cluster-1
        vm_name: "vm-test-demo"
        template_name: "rhel9-template"
        template_folder: "Workloads/sandbox-j7ttn"
        vm_folder: "Workloads/sandbox-j7ttn"

#    - name: Modify VM Configuration
#      vmware.vmware.vm:
#        name: "vm-demo-1"
#        cpu:
#          cores: 4
#          cores_per_socket: 2
#        memory: 
#          size_mb: 6144
#        disks:
#          - size_gb: 40
#            provisioning: thin
#            device_node: SCSI(0:0)
#        scsi_controllers:
#          - controller_type: paravirtual
#            bus_number: 0
#        network_adapters:
#          - network: segment-sandbox-j7ttn
#            adapter_type: vmxnet3
#            connected: true
#      register: vm_result