---
- name: Deploy VM from Folder Template
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get IP from vCenter
      vmware.vmware.guest_info:
        vcenter_validate_certs: false
        name: "vm-test-demo"
      register: vm_info

    - name: Display VM information
      debug:
        var: vm_info