---
- name: Gather VM Facts
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Get Guest Information from vCenter
      vmware.vmware.guest_info:
        validate_certs: false
        name: "vm-test-demo"
      register: vm_info