---
- name: Deploy VM from Folder Template
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create VM from template
      vmware.vmware.deploy_folder_template:
        validate_certs: false
        datacenter: "SDDC-Datacenter"
        cluster: Cluster-1
        vm_name: "vm-test-demo"
        template_name: "rhel9-template"
        template_folder: "Workloads/sandbox-j7ttn"
        vm_folder: "Workloads/sandbox-j7ttn"

    - name: Set the state of a virtual machine to poweron
      vmware.vmware.vm_powerstate:
        datacenter: "SDDC-Datacenter"
        folder: "Workloads/sandbox-j7ttn"
        name: "vm-test-demo"
        validate_certs: false
        state: powered-on
      register: poweron

    - name: Pause for 60 seconds
      ansible.builtin.pause:
        seconds: 60

    - name: Get IP from vCenter
      vmware.vmware.guest_info:
        validate_certs: false
        name: "vm-test-demo"
      register: vm_info

    - name: Display VM information
      debug:
        var: vm_info.guests[0].ipv4